quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

quarkus.http.port=${QUARKUS_HTTP_PORT:8083}

# Raw Transactions In - Konsumiert Transaktionen aus dem raw-transactions Topic
# Raw Transactions In - Consumes transactions from the raw-transactions topic
mp.messaging.incoming.raw-transactions-in.connector=smallrye-kafka
mp.messaging.incoming.raw-transactions-in.topic=raw-transactions
mp.messaging.incoming.raw-transactions-in.group.id=fraud-check-group

# Valid Transactions Out - Sendet gültige Transaktionen an das valid-transactions Topic
# Valid Transactions Out - Sends valid transactions to the valid-transactions topic
mp.messaging.outgoing.valid-transactions-out.connector=smallrye-kafka
mp.messaging.outgoing.valid-transactions-out.topic=valid-transactions
mp.messaging.outgoing.valid-transactions-out.partitioner=org.apache.kafka.clients.producer.RoundRobinPartitioner

# Fraud Alerts Out - Sendet Fraud Alerts an das fraud-alerts Topic
# Fraud Alerts Out - Sends fraud alerts to the fraud-alerts topic
mp.messaging.outgoing.fraud-alerts-out.connector=smallrye-kafka
mp.messaging.outgoing.fraud-alerts-out.topic=fraud-alerts

